report_task:
  description: >
    Based on the input topic {topic}, generate a detailed report including all the 
    lastest facts and future trends in a structured way. the report shoud be around
    2000 words,
  expected_output: >
    2000 words long report on the topic: {topic}
  agent: report_generator

blog_writing_task:
  description: >
    Based on the report on {topic}, create a well written and structured blog that 
    even a 5 year old can understand. the blog should be around 500 words.
  expected_output: >
    500 words long blog on the topic: {topic}. the blog shoud be well stturctured 
    with a creative and fun heading.
  agent: blog_writer
